# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod download
builds:
  - main: ./cmd/protoc-gen-go-errors
    id: "protoc-gen-go-errors"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: protoc-gen-go-errors
    ldflags:
      - -s -w -X main.version={{.Version}}
  - main: ./cmd/protoc-gen-go-test
    id: "protoc-gen-go-test"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: protoc-gen-go-test
    ldflags:
      - -s -w -X main.version={{.Version}}
archives:
  - name_template: "protoc-gen-go-errors-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
