package main

import (
	"testing"

	"github.com/gotomicro/ego/internal/tools"
	"github.com/stretchr/testify/assert"
)

func TestGenAst(t *testing.T) {
	content := `
// Code generated by protoc-gen-go-test. DO NOT EDIT.
package grpc

import (
    "testing"
)

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=false
func TestLogin1(t *testing.T) {
    t.Log("ok")
}

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=true
func TestLogin2(t *testing.T) {
    // HAS BEEN OVERRIDE
    // PLEASE DO NOT OVERRIDE BY progoc-gen-go-errors
	t.Log("111")
    t.Log("ok")
}
`
	tempContent := `
// Code generated by protoc-gen-go-test. DO NOT EDIT.
package grpc

import (
    "testing"
)

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=false
func TestLogin1(t *testing.T) {
    t.Log("ok")
}

// TestLoginOverride generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=false
func TestLogin2(t *testing.T) {
    t.Log("ok")
}

// TestLoginNew generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=false
func TestLogin3(t *testing.T) {
    t.Log("ok")
}
`
	want := string(tools.GoFmt([]byte(`
// Code generated by protoc-gen-go-test. DO NOT EDIT.
package grpc

import (
    "testing"
)

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=false
func TestLogin1(t *testing.T) {
    t.Log("ok")
}

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=true
func TestLogin2(t *testing.T) {
    // HAS BEEN OVERRIDE
    // PLEASE DO NOT OVERRIDE BY progoc-gen-go-errors
	t.Log("111")
    t.Log("ok")
}

// TestLoginNew generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Time=2021-09-14T14:48:18
// @Override=false
func TestLogin3(t *testing.T) {
    t.Log("ok")
}
`)))
	mergedFile, err := genFinalContent([]byte(content), []byte(tempContent))
	assert.NoError(t, err)
	assert.Equal(t, want, string(mergedFile))
}
