package main

import (
	"testing"

	"github.com/gotomicro/ego/internal/tools"
	"github.com/stretchr/testify/assert"
)

func TestGenAst(t *testing.T) {
	originContent := `
// Code generated by protoc-gen-go-test. DO NOT EDIT.
package grpc

import (
    "testing"

	_ "mycustom/pkg"
)

// myCustomType declare a custom type
type myCustomType struct{}

// myCustomInt1 declare a custom integer
var myCustomInt1 int

// myCustomInt2 declare a custom integer
var myCustomInt2 int

// myCustomFunc declare a custom function
func myCustomFunc() { 
	// nil return
	return nil 
}

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=false
func TestLogin1(t *testing.T) {
    t.Log("ok")
}

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=true
func TestLogin2(t *testing.T) {
    // HAS BEEN OVERRIDE
    // PLEASE DO NOT OVERRIDE BY progoc-gen-go-errors
	t.Log("111")
    t.Log("ok")
}
`
	tempContent := `
// Code generated by protoc-gen-go-test. DO NOT EDIT.
package grpc

import (
    "testing"
)

// genInt generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=true
var genInt int

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=false
func TestLogin1(t *testing.T) {
    t.Log("ok")
}

// TestLoginOverride generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=false
func TestLogin2(t *testing.T) {
    t.Log("ok")
}

// TestLoginNew generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=false
func TestLogin3(t *testing.T) {
    t.Log("ok")
}
`
	want := string(tools.GoFmt([]byte(`
// Code generated by protoc-gen-go-test. DO NOT EDIT.
package grpc

import (
    "testing"

	_ "mycustom/pkg"
)

// myCustomType declare a custom type
type myCustomType struct{}

// myCustomInt1 declare a custom integer
var myCustomInt1 int

// myCustomInt2 declare a custom integer
var myCustomInt2 int

// genInt generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=true
var genInt int

// myCustomFunc declare a custom function 
func myCustomFunc() { 
	// nil return
	return nil 
}

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=false
func TestLogin1(t *testing.T) {
    t.Log("ok")
}

// TestLogin generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=true
func TestLogin2(t *testing.T) {
    // HAS BEEN OVERRIDE
    // PLEASE DO NOT OVERRIDE BY progoc-gen-go-errors
	t.Log("111")
    t.Log("ok")
}

// TestLoginNew generated by protoc-gen-go-test, you can fill test logic by yourself.
// @Override=false
func TestLogin3(t *testing.T) {
    t.Log("ok")
}
`)))
	mergedFile, err := genFinalContent([]byte(originContent), []byte(tempContent))
	assert.NoError(t, err)
	assert.Equal(t, want, string(mergedFile))
}
