package main

import (
	"bytes"
	"fmt"
	"log"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"

	"github.com/gotomicro/ego/internal/tools"
	"google.golang.org/protobuf/compiler/protogen"
)

var importTestPackages = map[string]string{
	"testing":                               "",
	"context":                               "",
	"github.com/stretchr/testify/assert":    "",
	"google.golang.org/grpc":                "",
	"google.golang.org/protobuf/proto":      "",
	"github.com/gotomicro/ego/client/egrpc": "cegrpc",
}

var importInitTestPackages = map[string]string{
	"net":                                   "",
	"context":                               "",
	"google.golang.org/grpc/test/bufconn":   "",
	"github.com/gotomicro/ego/server/egrpc": "",
}

func execCmd(name string, args ...string) (string, error) {
	cmd := exec.Command(name, args...)
	var outb, errb bytes.Buffer
	cmd.Stdout = &outb
	cmd.Stderr = &errb
	err := cmd.Run()
	if err != nil {
		return outb.String(), fmt.Errorf("error: %s, %w", errb.String(), err)
	}
	return strings.TrimSpace(outb.String()), nil
}

func generateInitFile(gen *protogen.Plugin, out string, mod string) (*protogen.GeneratedFile, error) {
	cmdout, err := execCmd("go", "list", out)
	if err != nil {
		return nil, fmt.Errorf("get package path fail, %w", err)
	}
	outPkg := cmdout[strings.LastIndex(cmdout, "/")+1:]
	filename := filepath.Join(out, "init_test.go")
	g := gen.NewGeneratedFile(filename, "")
	g.P("// Code generated by protoc-gen-go-test. DO NOT EDIT.")
	g.P()
	g.P("package ", outPkg)
	g.P()
	g.P("import (")
	for path, name := range importInitTestPackages {
		g.P(fmt.Sprintf("%s \"%s\"", name, path))
	}
	g.P(")")
	tpl := template.New("init_test")
	buf := new(bytes.Buffer)
	err = template.Must(tpl.Parse(baseTpl)).Execute(buf, nil)
	if err != nil {
		log.Fatal("render tmpl fail", err)
	}
	g.P(string(tools.GoFmt(buf.Bytes())))
	return nil, nil
}

// generateFile generates a _errors.pb.go file containing ego errors definitions.
func generateFile(gen *protogen.Plugin, file *protogen.File, out string, mod string) (*protogen.GeneratedFile, error) {
	cmdout, err := execCmd("go", "list", out)
	if err != nil {
		return nil, fmt.Errorf("get package path fail, %w", err)
	}
	outPkg := cmdout[strings.LastIndex(cmdout, "/")+1:]
	filename := filepath.Join(out, filepath.Base(file.GeneratedFilenamePrefix+"_test.go"))
	file.GoImportPath = protogen.GoImportPath(filepath.Join(mod, string(file.GoImportPath)))
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-go-test. DO NOT EDIT.")
	g.P()
	g.P("package ", outPkg)
	g.P()
	g.P("import (")
	for path, name := range importTestPackages {
		g.P(fmt.Sprintf("%s \"%s\"", name, path))
	}
	g.P(fmt.Sprintf("%s %s", file.GoPackageName, file.GoImportPath))
	g.P(")")
	generateFileContent(gen, file, g)
	return g, nil
}

// generateFileContent generates the ego errors definitions, excluding the package statement.
func generateFileContent(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile) {
	g.P("// This is a compile-time assertion to ensure that this generated file")
	g.P("// is compatible with the ego package it is being compiled against.")
	g.P()
	index := 0
	for _, svc := range file.Services {
		if !generateTestSection(gen, file, g, svc) {
			index++
		}
	}
	// If all enums do not contain 'service', the current file is skipped
	if index == 0 {
		g.Skip()
	}
}

func generateTestSection(gen *protogen.Plugin, file *protogen.File, g *protogen.GeneratedFile, svc *protogen.Service) bool {
	var w svcWrapper
	for _, method := range svc.Methods {
		method.Desc.IsStreamingServer()
		d := &svcData{
			Name:              method.GoName,
			InType:            string(method.Input.Desc.Name()),
			OutType:           string(method.Output.Desc.Name()),
			Package:           string(file.GoPackageName),
			Service:           service{Name: svc.GoName},
			isStreamingServer: method.Desc.IsStreamingServer(),
			isStreamingClient: method.Desc.IsStreamingClient(),
		}
		w.Svcs = append(w.Svcs, d)
	}
	if len(w.Svcs) == 0 {
		return true
	}
	g.P(w.execute())
	return false
}
