run-client:export EGO_DEBUG=true
run-client:export EGO_LOG_EXTRA_KEYS=X-Ego-Uid
run-client:
	go run client/main.go --config=client/config.toml


run-server:export EGO_DEBUG=true
run-server:export EGO_LOG_EXTRA_KEYS=X-Ego-Uid
run-server:
	go run server/main.go --config=server/config.toml

