// Code generated by protoc-gen-go. DO NOT EDIT.
// source: log.pb

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Log struct {
	Time                 *uint32        `protobuf:"varint,1,req,name=Time" json:"Time,omitempty"`
	Contents             []*Log_Content `protobuf:"bytes,2,rep,name=Contents" json:"Contents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Log) Reset()         { *m = Log{} }
func (m *Log) String() string { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()    {}
func (*Log) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{0}
}

func (m *Log) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log.Unmarshal(m, b)
}
func (m *Log) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log.Marshal(b, m, deterministic)
}
func (m *Log) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log.Merge(m, src)
}
func (m *Log) XXX_Size() int {
	return xxx_messageInfo_Log.Size(m)
}
func (m *Log) XXX_DiscardUnknown() {
	xxx_messageInfo_Log.DiscardUnknown(m)
}

var xxx_messageInfo_Log proto.InternalMessageInfo

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*Log_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Log_Content struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Log_Content) Reset()         { *m = Log_Content{} }
func (m *Log_Content) String() string { return proto.CompactTextString(m) }
func (*Log_Content) ProtoMessage()    {}
func (*Log_Content) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{0, 0}
}

func (m *Log_Content) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Log_Content.Unmarshal(m, b)
}
func (m *Log_Content) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Log_Content.Marshal(b, m, deterministic)
}
func (m *Log_Content) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Log_Content.Merge(m, src)
}
func (m *Log_Content) XXX_Size() int {
	return xxx_messageInfo_Log_Content.Size(m)
}
func (m *Log_Content) XXX_DiscardUnknown() {
	xxx_messageInfo_Log_Content.DiscardUnknown(m)
}

var xxx_messageInfo_Log_Content proto.InternalMessageInfo

func (m *Log_Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Log_Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogTag struct {
	Key                  *string  `protobuf:"bytes,1,req,name=Key" json:"Key,omitempty"`
	Value                *string  `protobuf:"bytes,2,req,name=Value" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LogTag) Reset()         { *m = LogTag{} }
func (m *LogTag) String() string { return proto.CompactTextString(m) }
func (*LogTag) ProtoMessage()    {}
func (*LogTag) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{1}
}

func (m *LogTag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogTag.Unmarshal(m, b)
}
func (m *LogTag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogTag.Marshal(b, m, deterministic)
}
func (m *LogTag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogTag.Merge(m, src)
}
func (m *LogTag) XXX_Size() int {
	return xxx_messageInfo_LogTag.Size(m)
}
func (m *LogTag) XXX_DiscardUnknown() {
	xxx_messageInfo_LogTag.DiscardUnknown(m)
}

var xxx_messageInfo_LogTag proto.InternalMessageInfo

func (m *LogTag) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *LogTag) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs                 []*Log    `protobuf:"bytes,1,rep,name=Logs" json:"Logs,omitempty"`
	Category             *string   `protobuf:"bytes,2,opt,name=Category" json:"Category,omitempty"`
	Topic                *string   `protobuf:"bytes,3,opt,name=Topic" json:"Topic,omitempty"`
	Source               *string   `protobuf:"bytes,4,opt,name=Source" json:"Source,omitempty"`
	MachineUUID          *string   `protobuf:"bytes,5,opt,name=MachineUUID" json:"MachineUUID,omitempty"`
	LogTags              []*LogTag `protobuf:"bytes,6,rep,name=LogTags" json:"LogTags,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *LogGroup) Reset()         { *m = LogGroup{} }
func (m *LogGroup) String() string { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()    {}
func (*LogGroup) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{2}
}

func (m *LogGroup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroup.Unmarshal(m, b)
}
func (m *LogGroup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroup.Marshal(b, m, deterministic)
}
func (m *LogGroup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroup.Merge(m, src)
}
func (m *LogGroup) XXX_Size() int {
	return xxx_messageInfo_LogGroup.Size(m)
}
func (m *LogGroup) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroup.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroup proto.InternalMessageInfo

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetCategory() string {
	if m != nil && m.Category != nil {
		return *m.Category
	}
	return ""
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *LogGroup) GetMachineUUID() string {
	if m != nil && m.MachineUUID != nil {
		return *m.MachineUUID
	}
	return ""
}

func (m *LogGroup) GetLogTags() []*LogTag {
	if m != nil {
		return m.LogTags
	}
	return nil
}

type SlsLogPackage struct {
	Data                 []byte   `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	UncompressSize       *int32   `protobuf:"varint,2,opt,name=uncompress_size,json=uncompressSize" json:"uncompress_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SlsLogPackage) Reset()         { *m = SlsLogPackage{} }
func (m *SlsLogPackage) String() string { return proto.CompactTextString(m) }
func (*SlsLogPackage) ProtoMessage()    {}
func (*SlsLogPackage) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{3}
}

func (m *SlsLogPackage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlsLogPackage.Unmarshal(m, b)
}
func (m *SlsLogPackage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlsLogPackage.Marshal(b, m, deterministic)
}
func (m *SlsLogPackage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlsLogPackage.Merge(m, src)
}
func (m *SlsLogPackage) XXX_Size() int {
	return xxx_messageInfo_SlsLogPackage.Size(m)
}
func (m *SlsLogPackage) XXX_DiscardUnknown() {
	xxx_messageInfo_SlsLogPackage.DiscardUnknown(m)
}

var xxx_messageInfo_SlsLogPackage proto.InternalMessageInfo

func (m *SlsLogPackage) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SlsLogPackage) GetUncompressSize() int32 {
	if m != nil && m.UncompressSize != nil {
		return *m.UncompressSize
	}
	return 0
}

type SlsLogPackageList struct {
	Packages             []*SlsLogPackage `protobuf:"bytes,1,rep,name=packages" json:"packages,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SlsLogPackageList) Reset()         { *m = SlsLogPackageList{} }
func (m *SlsLogPackageList) String() string { return proto.CompactTextString(m) }
func (*SlsLogPackageList) ProtoMessage()    {}
func (*SlsLogPackageList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{4}
}

func (m *SlsLogPackageList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SlsLogPackageList.Unmarshal(m, b)
}
func (m *SlsLogPackageList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SlsLogPackageList.Marshal(b, m, deterministic)
}
func (m *SlsLogPackageList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SlsLogPackageList.Merge(m, src)
}
func (m *SlsLogPackageList) XXX_Size() int {
	return xxx_messageInfo_SlsLogPackageList.Size(m)
}
func (m *SlsLogPackageList) XXX_DiscardUnknown() {
	xxx_messageInfo_SlsLogPackageList.DiscardUnknown(m)
}

var xxx_messageInfo_SlsLogPackageList proto.InternalMessageInfo

func (m *SlsLogPackageList) GetPackages() []*SlsLogPackage {
	if m != nil {
		return m.Packages
	}
	return nil
}

type LogGroupList struct {
	LogGroupList         []*LogGroup `protobuf:"bytes,1,rep,name=logGroupList" json:"logGroupList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *LogGroupList) Reset()         { *m = LogGroupList{} }
func (m *LogGroupList) String() string { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()    {}
func (*LogGroupList) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2d5645e034ace88, []int{5}
}

func (m *LogGroupList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LogGroupList.Unmarshal(m, b)
}
func (m *LogGroupList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LogGroupList.Marshal(b, m, deterministic)
}
func (m *LogGroupList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LogGroupList.Merge(m, src)
}
func (m *LogGroupList) XXX_Size() int {
	return xxx_messageInfo_LogGroupList.Size(m)
}
func (m *LogGroupList) XXX_DiscardUnknown() {
	xxx_messageInfo_LogGroupList.DiscardUnknown(m)
}

var xxx_messageInfo_LogGroupList proto.InternalMessageInfo

func (m *LogGroupList) GetLogGroupList() []*LogGroup {
	if m != nil {
		return m.LogGroupList
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "pb.Log")
	proto.RegisterType((*Log_Content)(nil), "pb.Log.Content")
	proto.RegisterType((*LogTag)(nil), "pb.LogTag")
	proto.RegisterType((*LogGroup)(nil), "pb.LogGroup")
	proto.RegisterType((*SlsLogPackage)(nil), "pb.SlsLogPackage")
	proto.RegisterType((*SlsLogPackageList)(nil), "pb.SlsLogPackageList")
	proto.RegisterType((*LogGroupList)(nil), "pb.LogGroupList")
}

func init() { proto.RegisterFile("log.pb", fileDescriptor_d2d5645e034ace88) }

var fileDescriptor_d2d5645e034ace88 = []byte{
	// 343 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x50, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0xa5, 0xed, 0xd6, 0x75, 0x77, 0x9d, 0x73, 0x41, 0x24, 0xcc, 0x97, 0x52, 0x04, 0x07, 0x62,
	0x99, 0x7e, 0x81, 0x38, 0x41, 0xc4, 0x08, 0x92, 0x75, 0xbe, 0x4a, 0x56, 0x43, 0x2c, 0x76, 0x4d,
	0x69, 0xda, 0x87, 0xed, 0xcf, 0xfc, 0x3b, 0x69, 0x9a, 0xcd, 0xed, 0xcd, 0xb7, 0x73, 0xce, 0x3d,
	0xf7, 0x70, 0xee, 0x05, 0x37, 0x93, 0x22, 0x2a, 0x56, 0xc8, 0x2e, 0x56, 0xe1, 0x06, 0x1c, 0x22,
	0x05, 0x42, 0xd0, 0x89, 0xd3, 0x35, 0xc7, 0x56, 0x60, 0x4f, 0x87, 0x54, 0x63, 0x74, 0x0d, 0xde,
	0x5c, 0xe6, 0x15, 0xcf, 0x2b, 0x85, 0xed, 0xc0, 0x99, 0x0e, 0xee, 0x46, 0x51, 0xb1, 0x8a, 0x88,
	0x14, 0x91, 0xd1, 0xe9, 0xde, 0x30, 0xb9, 0x85, 0x9e, 0xc1, 0xe8, 0x14, 0x9c, 0x17, 0xbe, 0xd1,
	0x51, 0x7d, 0xda, 0x40, 0x74, 0x06, 0xdd, 0x77, 0x96, 0xd5, 0x1c, 0xdb, 0x5a, 0x6b, 0x49, 0x38,
	0x03, 0x97, 0x48, 0x11, 0x33, 0xf1, 0xef, 0x8d, 0x1f, 0x0b, 0x3c, 0x22, 0xc5, 0x53, 0x29, 0xeb,
	0x02, 0x5d, 0x40, 0x87, 0x48, 0xa1, 0xb0, 0xa5, 0xab, 0xf5, 0x4c, 0x35, 0xaa, 0x45, 0x34, 0x01,
	0x6f, 0xce, 0x2a, 0x2e, 0x64, 0xb9, 0xc1, 0x76, 0x60, 0x4d, 0xfb, 0x74, 0xcf, 0x9b, 0xec, 0x58,
	0x16, 0x69, 0x82, 0x1d, 0x3d, 0x68, 0x09, 0x3a, 0x07, 0x77, 0x21, 0xeb, 0x32, 0xe1, 0xb8, 0xa3,
	0x65, 0xc3, 0x50, 0x00, 0x83, 0x57, 0x96, 0x7c, 0xa5, 0x39, 0x5f, 0x2e, 0x9f, 0x1f, 0x71, 0x57,
	0x0f, 0x0f, 0x25, 0x74, 0x09, 0xbd, 0xf6, 0x0e, 0x85, 0x5d, 0xdd, 0x05, 0x4c, 0x97, 0x98, 0x09,
	0xba, 0x1b, 0x85, 0x04, 0x86, 0x8b, 0x4c, 0x11, 0x29, 0xde, 0x58, 0xf2, 0xcd, 0x04, 0x6f, 0x5e,
	0xfe, 0xc9, 0x2a, 0xa6, 0xaf, 0xf6, 0xa9, 0xc6, 0xe8, 0x0a, 0x46, 0x75, 0x9e, 0xc8, 0x75, 0x51,
	0x72, 0xa5, 0x3e, 0x54, 0xba, 0xe5, 0xba, 0x7d, 0x97, 0x9e, 0xfc, 0xc9, 0x8b, 0x74, 0xcb, 0xc3,
	0x07, 0x18, 0x1f, 0xa5, 0x91, 0x54, 0x55, 0xe8, 0x06, 0xbc, 0xa2, 0xa5, 0xbb, 0xaf, 0x8c, 0x9b,
	0x26, 0x47, 0x46, 0xba, 0xb7, 0x84, 0xf7, 0xe0, 0xef, 0x9e, 0xa9, 0xd7, 0x67, 0xe0, 0x67, 0x07,
	0xdc, 0x44, 0xf8, 0xe6, 0x18, 0xad, 0xd3, 0x23, 0xc7, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xe8,
	0x8f, 0xce, 0x9a, 0x49, 0x02, 0x00, 0x00,
}
