// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.1.0
// - protoc             v3.17.3
// source: helloworld.proto

package helloworld

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	SayHelloUnary2Stream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloUnary2StreamClient, error)
	SayHelloStream2Unary(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStream2UnaryClient, error)
	SayHelloStream2Stream(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStream2StreamClient, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/helloworld.Greeter/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SayHelloUnary2Stream(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloUnary2StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[0], "/helloworld.Greeter/SayHelloUnary2Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloUnary2StreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHelloUnary2StreamClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greeterSayHelloUnary2StreamClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloUnary2StreamClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloStream2Unary(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStream2UnaryClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[1], "/helloworld.Greeter/SayHelloStream2Unary", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStream2UnaryClient{stream}
	return x, nil
}

type Greeter_SayHelloStream2UnaryClient interface {
	Send(*HelloRequest) error
	CloseAndRecv() (*HelloResponse, error)
	grpc.ClientStream
}

type greeterSayHelloStream2UnaryClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStream2UnaryClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloStream2UnaryClient) CloseAndRecv() (*HelloResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greeterClient) SayHelloStream2Stream(ctx context.Context, opts ...grpc.CallOption) (Greeter_SayHelloStream2StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greeter_ServiceDesc.Streams[2], "/helloworld.Greeter/SayHelloStream2Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloStream2StreamClient{stream}
	return x, nil
}

type Greeter_SayHelloStream2StreamClient interface {
	Send(*HelloRequest) error
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greeterSayHelloStream2StreamClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloStream2StreamClient) Send(m *HelloRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greeterSayHelloStream2StreamClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
// All implementations must embed UnimplementedGreeterServer
// for forward compatibility
type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	SayHelloUnary2Stream(*HelloRequest, Greeter_SayHelloUnary2StreamServer) error
	SayHelloStream2Unary(Greeter_SayHelloStream2UnaryServer) error
	SayHelloStream2Stream(Greeter_SayHelloStream2StreamServer) error
	mustEmbedUnimplementedGreeterServer()
}

// UnimplementedGreeterServer must be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (UnimplementedGreeterServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreeterServer) SayHelloUnary2Stream(*HelloRequest, Greeter_SayHelloUnary2StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloUnary2Stream not implemented")
}
func (UnimplementedGreeterServer) SayHelloStream2Unary(Greeter_SayHelloStream2UnaryServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStream2Unary not implemented")
}
func (UnimplementedGreeterServer) SayHelloStream2Stream(Greeter_SayHelloStream2StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHelloStream2Stream not implemented")
}
func (UnimplementedGreeterServer) mustEmbedUnimplementedGreeterServer() {}

// UnsafeGreeterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreeterServer will
// result in compilation errors.
type UnsafeGreeterServer interface {
	mustEmbedUnimplementedGreeterServer()
}

func RegisterGreeterServer(s grpc.ServiceRegistrar, srv GreeterServer) {
	s.RegisterService(&Greeter_ServiceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/helloworld.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SayHelloUnary2Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHelloUnary2Stream(m, &greeterSayHelloUnary2StreamServer{stream})
}

type Greeter_SayHelloUnary2StreamServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greeterSayHelloUnary2StreamServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloUnary2StreamServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Greeter_SayHelloStream2Unary_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloStream2Unary(&greeterSayHelloStream2UnaryServer{stream})
}

type Greeter_SayHelloStream2UnaryServer interface {
	SendAndClose(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloStream2UnaryServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStream2UnaryServer) SendAndClose(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloStream2UnaryServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greeter_SayHelloStream2Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreeterServer).SayHelloStream2Stream(&greeterSayHelloStream2StreamServer{stream})
}

type Greeter_SayHelloStream2StreamServer interface {
	Send(*HelloResponse) error
	Recv() (*HelloRequest, error)
	grpc.ServerStream
}

type greeterSayHelloStream2StreamServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloStream2StreamServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greeterSayHelloStream2StreamServer) Recv() (*HelloRequest, error) {
	m := new(HelloRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greeter_ServiceDesc is the grpc.ServiceDesc for Greeter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greeter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHelloUnary2Stream",
			Handler:       _Greeter_SayHelloUnary2Stream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SayHelloStream2Unary",
			Handler:       _Greeter_SayHelloStream2Unary_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "SayHelloStream2Stream",
			Handler:       _Greeter_SayHelloStream2Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
