// Code generated by protoc-gen-go-test. DO NOT EDIT.

package server

import (
	"context"
	"github.com/gotomicro/ego/server/egrpc"
	"google.golang.org/grpc/test/bufconn"
	"net"
)

// svc generated by protoc-gen-go-test, you should not edit it.
// @Time=2021-09-14T21:27:44
// @Override=false
var svc *egrpc.Component

// init generated by protoc-gen-go-test, you can fill initial logic by yourself.
// @Time=2021-09-14T21:27:44
// @Override=false
func init() {
	// initial your configuration、DB instance、Redis instance here.
}

// bufDialer generated by protoc-gen-go-test, you should not edit it.
// @Time=2021-09-14T21:27:44
// @Override=false
func bufDialer(context.Context, string) (net.Conn, error) {
	return svc.Listener().(*bufconn.Listener).Dial()
}
